### ISSUE TITLE
Problem Seeds

### ISSUE THREAD

**Issue by solairflaire** [progre/lmorandomizer#1]
Seed: MazeofGalious
The Feather was in the Death Seal shop in Temple of the Sun, which requires the feather to reach or a damage boost. Damage boosting should probably not be required unless the player opts into it. 

Seed: Breakdown777
I'm not sure how the logic in this seed worked at all. I couldn't figure it out. I ended up damage boosting to the Death Seal shop to get the Bronze Mirror so I could get to the Tower of the Goddess, Then I damage boosted up the tower to continue the seed. I have no idea if any of that was required. I ran out of ideas on what to do.
Then I found the Hand Scanner in the normal Endless Key chest in the Infinite Corridor which normally requires the Treasure so you can get the Anchor. However, I found the Treasure in the normal Plane Model chest in the Tower of the Goddess, which requires you to read a tablet (which requires the Hand Scanner) so you can flood the tower. Clipping into a wall ended up being required to finish the seed since the Hand Scanner is required to read the mantra tablets.

I hope you keep up the good work on this. I'd like to see the "roadside" ROMs randomized into everything as well, assuming that's possible.

**Comment by progre** [comment]
Thank you for confirming.
Most of the pull requests have been accepted.
I have an idea to implement shuffling of roadside roms. It will be a while.
