### ISSUE TITLE
Subweapons Unable to Be Collected

### ISSUE THREAD

**Issue by nintendesi** [progre/lmorandomizer#24]
Repro seed: birthtest
Glyph Reader was in the shop by Elder Xelpud. After purchase, it was not placed in my items screen.

Repro seed: birthtest2
Shuriken subweapon in the second room of Guidance Gate. After collection, the subweapon did not go into my inventory.

Thank you so much for all of your work on this fantastic randomizer! I hope the feedback is helpful!

**Comment by nintendesi** [comment]
I have more feedback regarding this issue.

Repro seed: birthtest2
In Guidance Gate (room with fake spikes on the floor leading to Shurikens in the original), the randomizer had the Flare subweapon. I collected the Flares and these _did_ go in my inventory. It seems sometimes the subweapon can be collected and other times it cannot.

**Comment by progre** [comment]
Thanks for checking.
Randamize logic is not stable and seed results will be updated soon.

> Repro seed: birthtest

I tried with the version I had at hand, but Glyph Reader was not sold. If you clarify the version of the app and which store, I might be able to find it (Elder Xelpud does not have a store).

> Repro seed: birthtest2

Subweapons that appear on the roadside can be the main body or bullets. i plan to prevent subweapon bullets from appearing on the roadside.

**Comment by nintendesi** [comment]
Thanks for the clarification, now I understand why roadside subweapons sometimes will not go into the inventory currently.

Repro seed: birthtest

I apologize for the confusion. Correct, Elder Xelpud does not have a store. There is a screen with a single hut (with a shop) and a pot with ten coins inside. This is one screen to the left of Elder Xelpud's hut. Inside of that shop you should find the shop with the Glyph Reader for 10 coins. When I purchase the Glyph Reader, it does not go into my inventory.

**Comment by nintendesi** [comment]
Oh, looking back at the seed, I made a mistake. It was not the Glyph Reader for sale, but rather the Hand Scanner. After purchasing the Hand Scanner it does not go into the inventory.

**Comment by progre** [comment]
OK, I'm glad you got it sorted out.
