### ISSUE TITLE
Treasure and Pepper erase Anchor

### ISSUE THREAD

**Issue by progre** [progre/lmorandomizer#34]
![image](https://github.com/user-attachments/assets/f1a7de03-a7af-4a0a-bdf5-3bd004423fed)

The effects of Treasure and Pepper remain in effect even if overwritten by other items. This is because these effects are performed on flags, not items.
But Anchor is different: Anchor's effect is only performed if you own the item.

Thus, if you get Anchor and then Pepper or Treasure, you will get a softlock on Gate of Illusion (you can avoid this by using glitches).
More precisely, it is lost when the save data is loaded after acquiring a new item.

I can think of several ways to solve this.

- a. Revert the behavior of Treasure man and make it always serve Pepper, then Anchor.
- b. Place the Anchor in a visible location when the acquired flag of the Anchor has been established
    - This will not be confusing if the player does not know the game specs. However, this looks very bad.
- c. Similarly, obtain Anchor by destroying the jar.
    - The jar in this screen contains the weight. Once you have obtained Anchor, you must load the game to obtain Anchor again.
- d. Similarly, the corpse can be examined with a hand scanner and quietly acquired.
    - 「そんなガラクタを持ってどうするんだ？」The message is displayed. I would like someone to come up with an English translation.
    - It blends into the game world. But players may be confused if they don't know the specifications.

**Comment by progre** [comment]
I like d idea, but I am not sure if new players will understand how this works.
Will the remake have the same problem?

**Comment by progre** [comment]
Maybe the Amulet or Diary can disable the MuLana Talisman?
Need to check.

**Comment by progre** [comment]
Obj No. 220 The Curse of the Chest is checking the flag on the MuLana Talisman, it says. Probably not causing any problems.

I came up with a new idea.

- e. ~~check flags and overwrite with Obj No. 078 Water~~

This may be the best way to go.

Would Anchor have worked anywhere else but here?

**Comment by progre** [comment]
![Recording 2024-08-07 200949](https://github.com/user-attachments/assets/9e7bfc06-cae2-486e-9978-3560f60b56b0)

It looks a little bad, but it certainly works as normal water.

However, Anchor has the useful feature of sinking quickly into the water, not just here. It should still provide a way to retrieve the item again.

**Comment by jeremydk** [comment]
I personally like the idea of having Anchor work as much like a flag as we can. -- but option "C" also works as an easy fallback option to me.

**Comment by progre** [comment]
I came up with a very good logic.

If Pepper (Treasure) is acquired while holding an Anchor, an additional Anchor will appear in its place.
Furthermore, if Pepper (Treasure) is acquired without an Anchor, only the acquisition flag for the additional Anchor will be turned on.

Place this in each of the locations where Pepper and Treasure can be retrieved, and all should be well.
As soon as the respective item is acquired while holding the Anchor, the item will be overwritten with the Anchor and both functions will be available.

The script and pseudo-logic are as follows


```text
<OBJECT 94,x,y,0,793,793,6001>
<START 99999,1>
<START 778,1>
<START 6001,1>
</OBJECT>
<OBJECT 1,x,y,778,26,6001,-1>
<START 99999,1>
<START 6001,1>
<START 778,0>
<START 793,0>
</OBJECT>
```

```rust
let has_anchor; // FLAG 778
let has_pepper; // FLAG 793
// let has_treasure; // FLAG 794
let mut put_pepper_down = false; // NEW FLAG 6001
// let mut put_treasure_down = false; // NEW FLAG 6002

// OBJECT 94
if !has_anchor && !put_pepper_down { // START
    if has_pepper {
        put_pepper_down = true;
    }
}
// OBJECT 1
if !put_pepper_down && has_anchor && has_pepper { // START
    chest(Equipment::Anchor, || { put_pepper_down = true; });
}
```

**Comment by jeremydk** [comment]
I like that option a lot, very clean, and doesn't require outside knowledge.

**Comment by progre** [comment]
![image](https://github.com/user-attachments/assets/e710e416-642e-4d6c-b5a0-d568766d0b74)

It sucks.
After reviewing the recording, I was exploring without getting Anchor; I was looking at spoilerlog and got it wrong.

I actually overwrote Anchor with Pepper and Anchor worked. It didn't matter if I save-loaded it or not.

I'm off to trash the junk.
